[package]
name = "shamir_share"
version = "0.1.0"
authors = ["lovingzizi <turingjohn2015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "0.9.2"
rand = "0.7.3"
subtle = "2.2.2"